# Generated by Django 5.0.6 on 2024-07-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='description',
        ),
    ]
